version: 2.1
workflows:
  build_test_deploy:
    jobs:
      - build_test

jobs:
  build_test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install --user --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: ~/.local/bin/pytest

